# Generated by Django 5.0.2 on 2024-03-02 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('toll_per_cross', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('toll_per_extra_weight', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StationCross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_toll', models.BigIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('station_cross', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.stationcross')),
            ],
        ),
    ]
